# Generated by Django 4.1.1 on 2023-04-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_middle_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Доктор',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_middle_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('address', models.TextField(verbose_name='Адрес_проживания')),
                ('gender', models.CharField(max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name_plural': 'Пациент',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата_приема')),
                ('disease', models.TextField(verbose_name='Заболевание')),
                ('cost', models.FloatField(verbose_name='Стоимость_приема')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor', verbose_name='Доктор')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name_plural': 'Прием',
            },
        ),
    ]
